[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "fdi-pln2611"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "click>=8.0.0",
    "requests>=2.28.0",
]

[project.scripts]
fdi-pln-2611-p1 = "src.config:cli"

[tool.uv]
package = true

[tool.hatch.build.targets.wheel]
packages = ["src"]
